### ISSUE TITLE
[Enhancement] 방 만들기에 네이밍 형식 추가

### ISSUE THREAD

**Issue by GosuEE** [Trys-Ketch/trys-ketch-client#122]
## 요약
방 만들기에 네이밍 규칙이 표시되지 않아 사용에 어려움이 있음

## 완료조건
- [x] 네이밍 규칙을 helper text, 혹은 방 생성 모달에 표시함

## 테스트 케이스
- [x] 해당 규칙이 잘 표시되는지 테스트

**Comment by synuns** [comment]
엄격한규칙이 필요한 경우가 아니기 때문에 toast 메시지를 보완하는 식으로 수정했습니다. UX가 향상되었습니다!
