### ISSUE TITLE
[Fix] webRTC 연결이 유지되던 문제

### ISSUE THREAD

**Issue by GosuEE** [Trys-Ketch/trys-ketch-client#25]
## 요약
webRTC연결 이후, 방을 나가도 연결이 유지되던 문제

## 완료조건
- [x] 각 peer당 webRTC 연결이 해제되어야함
- [x] 로컬에서 사용중인 마이크를 사용 중지해야함

## 테스트 케이스
GameRoom에서 나갔을 시 useEffect의 return문에서 RTC연결과 MediaStreamTrack을 disable해야함

**Comment by synuns** [comment]
해당 pr로 이슈가 해결된 것을 확인했습니다!
